// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/sweeney/identity/internal/service (interfaces: UserServicer)
//
// Generated by this command:
//
//	mockgen -destination=../mocks/mock_user_service.go -package=mocks github.com/sweeney/identity/internal/service UserServicer
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	domain "github.com/sweeney/identity/internal/domain"
	service "github.com/sweeney/identity/internal/service"
	gomock "go.uber.org/mock/gomock"
)

// MockUserServicer is a mock of UserServicer interface.
type MockUserServicer struct {
	ctrl     *gomock.Controller
	recorder *MockUserServicerMockRecorder
	isgomock struct{}
}

// MockUserServicerMockRecorder is the mock recorder for MockUserServicer.
type MockUserServicerMockRecorder struct {
	mock *MockUserServicer
}

// NewMockUserServicer creates a new mock instance.
func NewMockUserServicer(ctrl *gomock.Controller) *MockUserServicer {
	mock := &MockUserServicer{ctrl: ctrl}
	mock.recorder = &MockUserServicerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserServicer) EXPECT() *MockUserServicerMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockUserServicer) Create(username, displayName, password string, role domain.Role, meta ...service.AuditMeta) (*domain.User, error) {
	m.ctrl.T.Helper()
	varargs := []any{username, displayName, password, role}
	for _, a := range meta {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Create", varargs...)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockUserServicerMockRecorder) Create(username, displayName, password, role any, meta ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{username, displayName, password, role}, meta...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUserServicer)(nil).Create), varargs...)
}

// Delete mocks base method.
func (m *MockUserServicer) Delete(id string, meta ...service.AuditMeta) error {
	m.ctrl.T.Helper()
	varargs := []any{id}
	for _, a := range meta {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Delete", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockUserServicerMockRecorder) Delete(id any, meta ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{id}, meta...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockUserServicer)(nil).Delete), varargs...)
}

// GetByID mocks base method.
func (m *MockUserServicer) GetByID(id string) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", id)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockUserServicerMockRecorder) GetByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockUserServicer)(nil).GetByID), id)
}

// GetByUsername mocks base method.
func (m *MockUserServicer) GetByUsername(username string) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUsername", username)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUsername indicates an expected call of GetByUsername.
func (mr *MockUserServicerMockRecorder) GetByUsername(username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUsername", reflect.TypeOf((*MockUserServicer)(nil).GetByUsername), username)
}

// List mocks base method.
func (m *MockUserServicer) List() ([]*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List")
	ret0, _ := ret[0].([]*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockUserServicerMockRecorder) List() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockUserServicer)(nil).List))
}

// Update mocks base method.
func (m *MockUserServicer) Update(id string, input service.UpdateUserInput, meta ...service.AuditMeta) (*domain.User, error) {
	m.ctrl.T.Helper()
	varargs := []any{id, input}
	for _, a := range meta {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Update", varargs...)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockUserServicerMockRecorder) Update(id, input any, meta ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{id, input}, meta...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockUserServicer)(nil).Update), varargs...)
}
