// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/sweeney/identity/internal/domain (interfaces: BackupService)
//
// Generated by this command:
//
//	mockgen -destination=../mocks/mock_backup_service.go -package=mocks github.com/sweeney/identity/internal/domain BackupService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockBackupService is a mock of BackupService interface.
type MockBackupService struct {
	ctrl     *gomock.Controller
	recorder *MockBackupServiceMockRecorder
	isgomock struct{}
}

// MockBackupServiceMockRecorder is the mock recorder for MockBackupService.
type MockBackupServiceMockRecorder struct {
	mock *MockBackupService
}

// NewMockBackupService creates a new mock instance.
func NewMockBackupService(ctrl *gomock.Controller) *MockBackupService {
	mock := &MockBackupService{ctrl: ctrl}
	mock.recorder = &MockBackupServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBackupService) EXPECT() *MockBackupServiceMockRecorder {
	return m.recorder
}

// RunNow mocks base method.
func (m *MockBackupService) RunNow() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunNow")
	ret0, _ := ret[0].(error)
	return ret0
}

// RunNow indicates an expected call of RunNow.
func (mr *MockBackupServiceMockRecorder) RunNow() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunNow", reflect.TypeOf((*MockBackupService)(nil).RunNow))
}

// TriggerAsync mocks base method.
func (m *MockBackupService) TriggerAsync() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "TriggerAsync")
}

// TriggerAsync indicates an expected call of TriggerAsync.
func (mr *MockBackupServiceMockRecorder) TriggerAsync() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TriggerAsync", reflect.TypeOf((*MockBackupService)(nil).TriggerAsync))
}
