// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/sweeney/identity/internal/service (interfaces: OAuthServicer)
//
// Generated by this command:
//
//	mockgen -destination=../mocks/mock_oauth_service.go -package=mocks github.com/sweeney/identity/internal/service OAuthServicer
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	domain "github.com/sweeney/identity/internal/domain"
	service "github.com/sweeney/identity/internal/service"
	gomock "go.uber.org/mock/gomock"
)

// MockOAuthServicer is a mock of OAuthServicer interface.
type MockOAuthServicer struct {
	ctrl     *gomock.Controller
	recorder *MockOAuthServicerMockRecorder
	isgomock struct{}
}

// MockOAuthServicerMockRecorder is the mock recorder for MockOAuthServicer.
type MockOAuthServicerMockRecorder struct {
	mock *MockOAuthServicer
}

// NewMockOAuthServicer creates a new mock instance.
func NewMockOAuthServicer(ctrl *gomock.Controller) *MockOAuthServicer {
	mock := &MockOAuthServicer{ctrl: ctrl}
	mock.recorder = &MockOAuthServicerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOAuthServicer) EXPECT() *MockOAuthServicerMockRecorder {
	return m.recorder
}

// Authorize mocks base method.
func (m *MockOAuthServicer) Authorize(clientID, redirectURI, username, password, codeChallenge, ip string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Authorize", clientID, redirectURI, username, password, codeChallenge, ip)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Authorize indicates an expected call of Authorize.
func (mr *MockOAuthServicerMockRecorder) Authorize(clientID, redirectURI, username, password, codeChallenge, ip any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Authorize", reflect.TypeOf((*MockOAuthServicer)(nil).Authorize), clientID, redirectURI, username, password, codeChallenge, ip)
}

// AuthorizeByUserID mocks base method.
func (m *MockOAuthServicer) AuthorizeByUserID(clientID, redirectURI, userID, username, codeChallenge, ip string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AuthorizeByUserID", clientID, redirectURI, userID, username, codeChallenge, ip)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AuthorizeByUserID indicates an expected call of AuthorizeByUserID.
func (mr *MockOAuthServicerMockRecorder) AuthorizeByUserID(clientID, redirectURI, userID, username, codeChallenge, ip any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AuthorizeByUserID", reflect.TypeOf((*MockOAuthServicer)(nil).AuthorizeByUserID), clientID, redirectURI, userID, username, codeChallenge, ip)
}

// ExchangeCode mocks base method.
func (m *MockOAuthServicer) ExchangeCode(clientID, code, redirectURI, codeVerifier string) (*service.LoginResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExchangeCode", clientID, code, redirectURI, codeVerifier)
	ret0, _ := ret[0].(*service.LoginResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExchangeCode indicates an expected call of ExchangeCode.
func (mr *MockOAuthServicerMockRecorder) ExchangeCode(clientID, code, redirectURI, codeVerifier any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExchangeCode", reflect.TypeOf((*MockOAuthServicer)(nil).ExchangeCode), clientID, code, redirectURI, codeVerifier)
}

// GetClient mocks base method.
func (m *MockOAuthServicer) GetClient(clientID string) (*domain.OAuthClient, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClient", clientID)
	ret0, _ := ret[0].(*domain.OAuthClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetClient indicates an expected call of GetClient.
func (mr *MockOAuthServicerMockRecorder) GetClient(clientID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClient", reflect.TypeOf((*MockOAuthServicer)(nil).GetClient), clientID)
}

// IssueClientCredentials mocks base method.
func (m *MockOAuthServicer) IssueClientCredentials(client *domain.OAuthClient, requestedScope, ip string) (*service.ClientCredentialsResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IssueClientCredentials", client, requestedScope, ip)
	ret0, _ := ret[0].(*service.ClientCredentialsResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IssueClientCredentials indicates an expected call of IssueClientCredentials.
func (mr *MockOAuthServicerMockRecorder) IssueClientCredentials(client, requestedScope, ip any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IssueClientCredentials", reflect.TypeOf((*MockOAuthServicer)(nil).IssueClientCredentials), client, requestedScope, ip)
}

// RefreshToken mocks base method.
func (m *MockOAuthServicer) RefreshToken(rawRefreshToken string) (*service.LoginResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshToken", rawRefreshToken)
	ret0, _ := ret[0].(*service.LoginResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RefreshToken indicates an expected call of RefreshToken.
func (mr *MockOAuthServicerMockRecorder) RefreshToken(rawRefreshToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshToken", reflect.TypeOf((*MockOAuthServicer)(nil).RefreshToken), rawRefreshToken)
}

// ValidateAuthorizeRequest mocks base method.
func (m *MockOAuthServicer) ValidateAuthorizeRequest(clientID, redirectURI string) (*domain.OAuthClient, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateAuthorizeRequest", clientID, redirectURI)
	ret0, _ := ret[0].(*domain.OAuthClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateAuthorizeRequest indicates an expected call of ValidateAuthorizeRequest.
func (mr *MockOAuthServicerMockRecorder) ValidateAuthorizeRequest(clientID, redirectURI any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateAuthorizeRequest", reflect.TypeOf((*MockOAuthServicer)(nil).ValidateAuthorizeRequest), clientID, redirectURI)
}
