// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/sweeney/identity/internal/domain (interfaces: WebAuthnChallengeRepository)
//
// Generated by this command:
//
//	mockgen -destination=../mocks/mock_webauthn_challenge_repository.go -package=mocks github.com/sweeney/identity/internal/domain WebAuthnChallengeRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	domain "github.com/sweeney/identity/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockWebAuthnChallengeRepository is a mock of WebAuthnChallengeRepository interface.
type MockWebAuthnChallengeRepository struct {
	ctrl     *gomock.Controller
	recorder *MockWebAuthnChallengeRepositoryMockRecorder
	isgomock struct{}
}

// MockWebAuthnChallengeRepositoryMockRecorder is the mock recorder for MockWebAuthnChallengeRepository.
type MockWebAuthnChallengeRepositoryMockRecorder struct {
	mock *MockWebAuthnChallengeRepository
}

// NewMockWebAuthnChallengeRepository creates a new mock instance.
func NewMockWebAuthnChallengeRepository(ctrl *gomock.Controller) *MockWebAuthnChallengeRepository {
	mock := &MockWebAuthnChallengeRepository{ctrl: ctrl}
	mock.recorder = &MockWebAuthnChallengeRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWebAuthnChallengeRepository) EXPECT() *MockWebAuthnChallengeRepositoryMockRecorder {
	return m.recorder
}

// Consume mocks base method.
func (m *MockWebAuthnChallengeRepository) Consume(id string) (*domain.WebAuthnChallenge, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Consume", id)
	ret0, _ := ret[0].(*domain.WebAuthnChallenge)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Consume indicates an expected call of Consume.
func (mr *MockWebAuthnChallengeRepositoryMockRecorder) Consume(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Consume", reflect.TypeOf((*MockWebAuthnChallengeRepository)(nil).Consume), id)
}

// Create mocks base method.
func (m *MockWebAuthnChallengeRepository) Create(ch *domain.WebAuthnChallenge) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ch)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockWebAuthnChallengeRepositoryMockRecorder) Create(ch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockWebAuthnChallengeRepository)(nil).Create), ch)
}

// Delete mocks base method.
func (m *MockWebAuthnChallengeRepository) Delete(id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockWebAuthnChallengeRepositoryMockRecorder) Delete(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockWebAuthnChallengeRepository)(nil).Delete), id)
}

// DeleteExpired mocks base method.
func (m *MockWebAuthnChallengeRepository) DeleteExpired() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteExpired")
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteExpired indicates an expected call of DeleteExpired.
func (mr *MockWebAuthnChallengeRepositoryMockRecorder) DeleteExpired() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteExpired", reflect.TypeOf((*MockWebAuthnChallengeRepository)(nil).DeleteExpired))
}

// GetByID mocks base method.
func (m *MockWebAuthnChallengeRepository) GetByID(id string) (*domain.WebAuthnChallenge, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", id)
	ret0, _ := ret[0].(*domain.WebAuthnChallenge)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockWebAuthnChallengeRepositoryMockRecorder) GetByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockWebAuthnChallengeRepository)(nil).GetByID), id)
}
