// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/sweeney/identity/internal/domain (interfaces: ClaimCodeRepository)
//
// Generated by this command:
//
//	mockgen -destination=../mocks/mock_claim_code_repository.go -package=mocks github.com/sweeney/identity/internal/domain ClaimCodeRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	time "time"

	domain "github.com/sweeney/identity/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockClaimCodeRepository is a mock of ClaimCodeRepository interface.
type MockClaimCodeRepository struct {
	ctrl     *gomock.Controller
	recorder *MockClaimCodeRepositoryMockRecorder
	isgomock struct{}
}

// MockClaimCodeRepositoryMockRecorder is the mock recorder for MockClaimCodeRepository.
type MockClaimCodeRepositoryMockRecorder struct {
	mock *MockClaimCodeRepository
}

// NewMockClaimCodeRepository creates a new mock instance.
func NewMockClaimCodeRepository(ctrl *gomock.Controller) *MockClaimCodeRepository {
	mock := &MockClaimCodeRepository{ctrl: ctrl}
	mock.recorder = &MockClaimCodeRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClaimCodeRepository) EXPECT() *MockClaimCodeRepositoryMockRecorder {
	return m.recorder
}

// Bind mocks base method.
func (m *MockClaimCodeRepository) Bind(id, userID string, boundAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Bind", id, userID, boundAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// Bind indicates an expected call of Bind.
func (mr *MockClaimCodeRepositoryMockRecorder) Bind(id, userID, boundAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Bind", reflect.TypeOf((*MockClaimCodeRepository)(nil).Bind), id, userID, boundAt)
}

// Create mocks base method.
func (m *MockClaimCodeRepository) Create(c *domain.ClaimCode) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", c)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockClaimCodeRepositoryMockRecorder) Create(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockClaimCodeRepository)(nil).Create), c)
}

// GetByHash mocks base method.
func (m *MockClaimCodeRepository) GetByHash(codeHash string) (*domain.ClaimCode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByHash", codeHash)
	ret0, _ := ret[0].(*domain.ClaimCode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByHash indicates an expected call of GetByHash.
func (mr *MockClaimCodeRepositoryMockRecorder) GetByHash(codeHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByHash", reflect.TypeOf((*MockClaimCodeRepository)(nil).GetByHash), codeHash)
}

// GetByID mocks base method.
func (m *MockClaimCodeRepository) GetByID(id string) (*domain.ClaimCode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", id)
	ret0, _ := ret[0].(*domain.ClaimCode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockClaimCodeRepositoryMockRecorder) GetByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockClaimCodeRepository)(nil).GetByID), id)
}

// ListByClient mocks base method.
func (m *MockClaimCodeRepository) ListByClient(clientID string) ([]*domain.ClaimCode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByClient", clientID)
	ret0, _ := ret[0].([]*domain.ClaimCode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByClient indicates an expected call of ListByClient.
func (mr *MockClaimCodeRepositoryMockRecorder) ListByClient(clientID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByClient", reflect.TypeOf((*MockClaimCodeRepository)(nil).ListByClient), clientID)
}

// Delete mocks base method.
func (m *MockClaimCodeRepository) Delete(id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockClaimCodeRepositoryMockRecorder) Delete(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockClaimCodeRepository)(nil).Delete), id)
}

// Revoke mocks base method.
func (m *MockClaimCodeRepository) Revoke(id string, revokedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Revoke", id, revokedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// Revoke indicates an expected call of Revoke.
func (mr *MockClaimCodeRepositoryMockRecorder) Revoke(id, revokedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Revoke", reflect.TypeOf((*MockClaimCodeRepository)(nil).Revoke), id, revokedAt)
}
