// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/sweeney/identity/internal/domain (interfaces: OAuthCodeRepository)
//
// Generated by this command:
//
//	mockgen -destination=../mocks/mock_oauth_code_repository.go -package=mocks github.com/sweeney/identity/internal/domain OAuthCodeRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	time "time"

	domain "github.com/sweeney/identity/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockOAuthCodeRepository is a mock of OAuthCodeRepository interface.
type MockOAuthCodeRepository struct {
	ctrl     *gomock.Controller
	recorder *MockOAuthCodeRepositoryMockRecorder
	isgomock struct{}
}

// MockOAuthCodeRepositoryMockRecorder is the mock recorder for MockOAuthCodeRepository.
type MockOAuthCodeRepositoryMockRecorder struct {
	mock *MockOAuthCodeRepository
}

// NewMockOAuthCodeRepository creates a new mock instance.
func NewMockOAuthCodeRepository(ctrl *gomock.Controller) *MockOAuthCodeRepository {
	mock := &MockOAuthCodeRepository{ctrl: ctrl}
	mock.recorder = &MockOAuthCodeRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOAuthCodeRepository) EXPECT() *MockOAuthCodeRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockOAuthCodeRepository) Create(code *domain.AuthCode) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", code)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockOAuthCodeRepositoryMockRecorder) Create(code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockOAuthCodeRepository)(nil).Create), code)
}

// DeleteExpiredAndUsed mocks base method.
func (m *MockOAuthCodeRepository) DeleteExpiredAndUsed() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteExpiredAndUsed")
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteExpiredAndUsed indicates an expected call of DeleteExpiredAndUsed.
func (mr *MockOAuthCodeRepositoryMockRecorder) DeleteExpiredAndUsed() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteExpiredAndUsed", reflect.TypeOf((*MockOAuthCodeRepository)(nil).DeleteExpiredAndUsed))
}

// GetByHash mocks base method.
func (m *MockOAuthCodeRepository) GetByHash(codeHash string) (*domain.AuthCode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByHash", codeHash)
	ret0, _ := ret[0].(*domain.AuthCode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByHash indicates an expected call of GetByHash.
func (mr *MockOAuthCodeRepositoryMockRecorder) GetByHash(codeHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByHash", reflect.TypeOf((*MockOAuthCodeRepository)(nil).GetByHash), codeHash)
}

// MarkUsed mocks base method.
func (m *MockOAuthCodeRepository) MarkUsed(id string, usedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkUsed", id, usedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkUsed indicates an expected call of MarkUsed.
func (mr *MockOAuthCodeRepositoryMockRecorder) MarkUsed(id, usedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkUsed", reflect.TypeOf((*MockOAuthCodeRepository)(nil).MarkUsed), id, usedAt)
}
