// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/sweeney/identity/internal/domain (interfaces: WebAuthnCredentialRepository)
//
// Generated by this command:
//
//	mockgen -destination=../mocks/mock_webauthn_credential_repository.go -package=mocks github.com/sweeney/identity/internal/domain WebAuthnCredentialRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	time "time"

	domain "github.com/sweeney/identity/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockWebAuthnCredentialRepository is a mock of WebAuthnCredentialRepository interface.
type MockWebAuthnCredentialRepository struct {
	ctrl     *gomock.Controller
	recorder *MockWebAuthnCredentialRepositoryMockRecorder
	isgomock struct{}
}

// MockWebAuthnCredentialRepositoryMockRecorder is the mock recorder for MockWebAuthnCredentialRepository.
type MockWebAuthnCredentialRepositoryMockRecorder struct {
	mock *MockWebAuthnCredentialRepository
}

// NewMockWebAuthnCredentialRepository creates a new mock instance.
func NewMockWebAuthnCredentialRepository(ctrl *gomock.Controller) *MockWebAuthnCredentialRepository {
	mock := &MockWebAuthnCredentialRepository{ctrl: ctrl}
	mock.recorder = &MockWebAuthnCredentialRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWebAuthnCredentialRepository) EXPECT() *MockWebAuthnCredentialRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockWebAuthnCredentialRepository) Create(cred *domain.WebAuthnCredential) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", cred)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockWebAuthnCredentialRepositoryMockRecorder) Create(cred any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockWebAuthnCredentialRepository)(nil).Create), cred)
}

// Delete mocks base method.
func (m *MockWebAuthnCredentialRepository) Delete(id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockWebAuthnCredentialRepositoryMockRecorder) Delete(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockWebAuthnCredentialRepository)(nil).Delete), id)
}

// DeleteAllForUser mocks base method.
func (m *MockWebAuthnCredentialRepository) DeleteAllForUser(userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAllForUser", userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAllForUser indicates an expected call of DeleteAllForUser.
func (mr *MockWebAuthnCredentialRepositoryMockRecorder) DeleteAllForUser(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAllForUser", reflect.TypeOf((*MockWebAuthnCredentialRepository)(nil).DeleteAllForUser), userID)
}

// GetByCredentialID mocks base method.
func (m *MockWebAuthnCredentialRepository) GetByCredentialID(credentialID []byte) (*domain.WebAuthnCredential, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByCredentialID", credentialID)
	ret0, _ := ret[0].(*domain.WebAuthnCredential)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByCredentialID indicates an expected call of GetByCredentialID.
func (mr *MockWebAuthnCredentialRepositoryMockRecorder) GetByCredentialID(credentialID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByCredentialID", reflect.TypeOf((*MockWebAuthnCredentialRepository)(nil).GetByCredentialID), credentialID)
}

// ListByUserID mocks base method.
func (m *MockWebAuthnCredentialRepository) ListByUserID(userID string) ([]*domain.WebAuthnCredential, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUserID", userID)
	ret0, _ := ret[0].([]*domain.WebAuthnCredential)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByUserID indicates an expected call of ListByUserID.
func (mr *MockWebAuthnCredentialRepositoryMockRecorder) ListByUserID(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUserID", reflect.TypeOf((*MockWebAuthnCredentialRepository)(nil).ListByUserID), userID)
}

// Rename mocks base method.
func (m *MockWebAuthnCredentialRepository) Rename(id, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rename", id, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// Rename indicates an expected call of Rename.
func (mr *MockWebAuthnCredentialRepositoryMockRecorder) Rename(id, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rename", reflect.TypeOf((*MockWebAuthnCredentialRepository)(nil).Rename), id, name)
}

// UpdateLastUsed mocks base method.
func (m *MockWebAuthnCredentialRepository) UpdateLastUsed(id string, t time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLastUsed", id, t)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLastUsed indicates an expected call of UpdateLastUsed.
func (mr *MockWebAuthnCredentialRepositoryMockRecorder) UpdateLastUsed(id, t any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLastUsed", reflect.TypeOf((*MockWebAuthnCredentialRepository)(nil).UpdateLastUsed), id, t)
}

// UpdateSignCount mocks base method.
func (m *MockWebAuthnCredentialRepository) UpdateSignCount(id string, signCount uint32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSignCount", id, signCount)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSignCount indicates an expected call of UpdateSignCount.
func (mr *MockWebAuthnCredentialRepositoryMockRecorder) UpdateSignCount(id, signCount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSignCount", reflect.TypeOf((*MockWebAuthnCredentialRepository)(nil).UpdateSignCount), id, signCount)
}
