// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/sweeney/identity/internal/service (interfaces: DeviceFlowServicer)
//
// Generated by this command:
//
//	mockgen -destination=../mocks/mock_device_flow_service.go -package=mocks github.com/sweeney/identity/internal/service DeviceFlowServicer
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	domain "github.com/sweeney/identity/internal/domain"
	service "github.com/sweeney/identity/internal/service"
	gomock "go.uber.org/mock/gomock"
)

// MockDeviceFlowServicer is a mock of DeviceFlowServicer interface.
type MockDeviceFlowServicer struct {
	ctrl     *gomock.Controller
	recorder *MockDeviceFlowServicerMockRecorder
	isgomock struct{}
}

// MockDeviceFlowServicerMockRecorder is the mock recorder for MockDeviceFlowServicer.
type MockDeviceFlowServicerMockRecorder struct {
	mock *MockDeviceFlowServicer
}

// NewMockDeviceFlowServicer creates a new mock instance.
func NewMockDeviceFlowServicer(ctrl *gomock.Controller) *MockDeviceFlowServicer {
	mock := &MockDeviceFlowServicer{ctrl: ctrl}
	mock.recorder = &MockDeviceFlowServicerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeviceFlowServicer) EXPECT() *MockDeviceFlowServicerMockRecorder {
	return m.recorder
}

// Approve mocks base method.
func (m *MockDeviceFlowServicer) Approve(rawCode, userID, username, ip string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Approve", rawCode, userID, username, ip)
	ret0, _ := ret[0].(error)
	return ret0
}

// Approve indicates an expected call of Approve.
func (mr *MockDeviceFlowServicerMockRecorder) Approve(rawCode, userID, username, ip any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Approve", reflect.TypeOf((*MockDeviceFlowServicer)(nil).Approve), rawCode, userID, username, ip)
}

// ClaimDevice mocks base method.
func (m *MockDeviceFlowServicer) ClaimDevice(clientID, rawClaimCode, scope, ip string) (*service.DeviceAuthorizationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClaimDevice", clientID, rawClaimCode, scope, ip)
	ret0, _ := ret[0].(*service.DeviceAuthorizationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClaimDevice indicates an expected call of ClaimDevice.
func (mr *MockDeviceFlowServicerMockRecorder) ClaimDevice(clientID, rawClaimCode, scope, ip any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClaimDevice", reflect.TypeOf((*MockDeviceFlowServicer)(nil).ClaimDevice), clientID, rawClaimCode, scope, ip)
}

// CreateClaimCodes mocks base method.
func (m *MockDeviceFlowServicer) CreateClaimCodes(clientID string, labels []string, ip string) ([]*service.ClaimCodeResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateClaimCodes", clientID, labels, ip)
	ret0, _ := ret[0].([]*service.ClaimCodeResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateClaimCodes indicates an expected call of CreateClaimCodes.
func (mr *MockDeviceFlowServicerMockRecorder) CreateClaimCodes(clientID, labels, ip any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateClaimCodes", reflect.TypeOf((*MockDeviceFlowServicer)(nil).CreateClaimCodes), clientID, labels, ip)
}

// Deny mocks base method.
func (m *MockDeviceFlowServicer) Deny(rawCode, ip string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Deny", rawCode, ip)
	ret0, _ := ret[0].(error)
	return ret0
}

// Deny indicates an expected call of Deny.
func (mr *MockDeviceFlowServicerMockRecorder) Deny(rawCode, ip any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Deny", reflect.TypeOf((*MockDeviceFlowServicer)(nil).Deny), rawCode, ip)
}

// IssueDeviceAuthorization mocks base method.
func (m *MockDeviceFlowServicer) IssueDeviceAuthorization(clientID, scope, ip string) (*service.DeviceAuthorizationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IssueDeviceAuthorization", clientID, scope, ip)
	ret0, _ := ret[0].(*service.DeviceAuthorizationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IssueDeviceAuthorization indicates an expected call of IssueDeviceAuthorization.
func (mr *MockDeviceFlowServicerMockRecorder) IssueDeviceAuthorization(clientID, scope, ip any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IssueDeviceAuthorization", reflect.TypeOf((*MockDeviceFlowServicer)(nil).IssueDeviceAuthorization), clientID, scope, ip)
}

// ListClaimCodes mocks base method.
func (m *MockDeviceFlowServicer) ListClaimCodes(clientID string) ([]*domain.ClaimCode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListClaimCodes", clientID)
	ret0, _ := ret[0].([]*domain.ClaimCode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListClaimCodes indicates an expected call of ListClaimCodes.
func (mr *MockDeviceFlowServicerMockRecorder) ListClaimCodes(clientID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListClaimCodes", reflect.TypeOf((*MockDeviceFlowServicer)(nil).ListClaimCodes), clientID)
}

// LookupForVerification mocks base method.
func (m *MockDeviceFlowServicer) LookupForVerification(rawCode string) (*service.DeviceApprovalView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LookupForVerification", rawCode)
	ret0, _ := ret[0].(*service.DeviceApprovalView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LookupForVerification indicates an expected call of LookupForVerification.
func (mr *MockDeviceFlowServicerMockRecorder) LookupForVerification(rawCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LookupForVerification", reflect.TypeOf((*MockDeviceFlowServicer)(nil).LookupForVerification), rawCode)
}

// PollForToken mocks base method.
func (m *MockDeviceFlowServicer) PollForToken(clientID, rawDeviceCode, ip string) (*service.LoginResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PollForToken", clientID, rawDeviceCode, ip)
	ret0, _ := ret[0].(*service.LoginResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PollForToken indicates an expected call of PollForToken.
func (mr *MockDeviceFlowServicerMockRecorder) PollForToken(clientID, rawDeviceCode, ip any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PollForToken", reflect.TypeOf((*MockDeviceFlowServicer)(nil).PollForToken), clientID, rawDeviceCode, ip)
}

// RevokeClaimCode mocks base method.
func (m *MockDeviceFlowServicer) RevokeClaimCode(id, ip string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeClaimCode", id, ip)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeClaimCode indicates an expected call of RevokeClaimCode.
func (mr *MockDeviceFlowServicerMockRecorder) RevokeClaimCode(id, ip any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeClaimCode", reflect.TypeOf((*MockDeviceFlowServicer)(nil).RevokeClaimCode), id, ip)
}
