// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/sweeney/identity/internal/domain (interfaces: DeviceAuthorizationRepository)
//
// Generated by this command:
//
//	mockgen -destination=../mocks/mock_device_authorization_repository.go -package=mocks github.com/sweeney/identity/internal/domain DeviceAuthorizationRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	time "time"

	domain "github.com/sweeney/identity/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockDeviceAuthorizationRepository is a mock of DeviceAuthorizationRepository interface.
type MockDeviceAuthorizationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockDeviceAuthorizationRepositoryMockRecorder
	isgomock struct{}
}

// MockDeviceAuthorizationRepositoryMockRecorder is the mock recorder for MockDeviceAuthorizationRepository.
type MockDeviceAuthorizationRepositoryMockRecorder struct {
	mock *MockDeviceAuthorizationRepository
}

// NewMockDeviceAuthorizationRepository creates a new mock instance.
func NewMockDeviceAuthorizationRepository(ctrl *gomock.Controller) *MockDeviceAuthorizationRepository {
	mock := &MockDeviceAuthorizationRepository{ctrl: ctrl}
	mock.recorder = &MockDeviceAuthorizationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeviceAuthorizationRepository) EXPECT() *MockDeviceAuthorizationRepositoryMockRecorder {
	return m.recorder
}

// Approve mocks base method.
func (m *MockDeviceAuthorizationRepository) Approve(id, userID string, approvedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Approve", id, userID, approvedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// Approve indicates an expected call of Approve.
func (mr *MockDeviceAuthorizationRepositoryMockRecorder) Approve(id, userID, approvedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Approve", reflect.TypeOf((*MockDeviceAuthorizationRepository)(nil).Approve), id, userID, approvedAt)
}

// Create mocks base method.
func (m *MockDeviceAuthorizationRepository) Create(da *domain.DeviceAuthorization) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", da)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockDeviceAuthorizationRepositoryMockRecorder) Create(da any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDeviceAuthorizationRepository)(nil).Create), da)
}

// DeleteExpired mocks base method.
func (m *MockDeviceAuthorizationRepository) DeleteExpired() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteExpired")
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteExpired indicates an expected call of DeleteExpired.
func (mr *MockDeviceAuthorizationRepositoryMockRecorder) DeleteExpired() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteExpired", reflect.TypeOf((*MockDeviceAuthorizationRepository)(nil).DeleteExpired))
}

// Deny mocks base method.
func (m *MockDeviceAuthorizationRepository) Deny(id string, deniedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Deny", id, deniedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// Deny indicates an expected call of Deny.
func (mr *MockDeviceAuthorizationRepositoryMockRecorder) Deny(id, deniedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Deny", reflect.TypeOf((*MockDeviceAuthorizationRepository)(nil).Deny), id, deniedAt)
}

// GetByDeviceHash mocks base method.
func (m *MockDeviceAuthorizationRepository) GetByDeviceHash(deviceCodeHash string) (*domain.DeviceAuthorization, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByDeviceHash", deviceCodeHash)
	ret0, _ := ret[0].(*domain.DeviceAuthorization)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByDeviceHash indicates an expected call of GetByDeviceHash.
func (mr *MockDeviceAuthorizationRepositoryMockRecorder) GetByDeviceHash(deviceCodeHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByDeviceHash", reflect.TypeOf((*MockDeviceAuthorizationRepository)(nil).GetByDeviceHash), deviceCodeHash)
}

// GetByUserCode mocks base method.
func (m *MockDeviceAuthorizationRepository) GetByUserCode(userCode string) (*domain.DeviceAuthorization, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserCode", userCode)
	ret0, _ := ret[0].(*domain.DeviceAuthorization)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserCode indicates an expected call of GetByUserCode.
func (mr *MockDeviceAuthorizationRepositoryMockRecorder) GetByUserCode(userCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserCode", reflect.TypeOf((*MockDeviceAuthorizationRepository)(nil).GetByUserCode), userCode)
}

// ListPendingByClaimID mocks base method.
func (m *MockDeviceAuthorizationRepository) ListPendingByClaimID(claimCodeID string) ([]*domain.DeviceAuthorization, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPendingByClaimID", claimCodeID)
	ret0, _ := ret[0].([]*domain.DeviceAuthorization)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPendingByClaimID indicates an expected call of ListPendingByClaimID.
func (mr *MockDeviceAuthorizationRepositoryMockRecorder) ListPendingByClaimID(claimCodeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPendingByClaimID", reflect.TypeOf((*MockDeviceAuthorizationRepository)(nil).ListPendingByClaimID), claimCodeID)
}

// MarkConsumed mocks base method.
func (m *MockDeviceAuthorizationRepository) MarkConsumed(id string, consumedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkConsumed", id, consumedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkConsumed indicates an expected call of MarkConsumed.
func (mr *MockDeviceAuthorizationRepositoryMockRecorder) MarkConsumed(id, consumedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkConsumed", reflect.TypeOf((*MockDeviceAuthorizationRepository)(nil).MarkConsumed), id, consumedAt)
}

// MarkPolled mocks base method.
func (m *MockDeviceAuthorizationRepository) MarkPolled(id string, polledAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkPolled", id, polledAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkPolled indicates an expected call of MarkPolled.
func (mr *MockDeviceAuthorizationRepositoryMockRecorder) MarkPolled(id, polledAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkPolled", reflect.TypeOf((*MockDeviceAuthorizationRepository)(nil).MarkPolled), id, polledAt)
}
