// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/sweeney/identity/internal/domain (interfaces: AuditRepository)
//
// Generated by this command:
//
//	mockgen -destination=../mocks/mock_audit_repository.go -package=mocks github.com/sweeney/identity/internal/domain AuditRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	domain "github.com/sweeney/identity/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockAuditRepository is a mock of AuditRepository interface.
type MockAuditRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAuditRepositoryMockRecorder
	isgomock struct{}
}

// MockAuditRepositoryMockRecorder is the mock recorder for MockAuditRepository.
type MockAuditRepositoryMockRecorder struct {
	mock *MockAuditRepository
}

// NewMockAuditRepository creates a new mock instance.
func NewMockAuditRepository(ctrl *gomock.Controller) *MockAuditRepository {
	mock := &MockAuditRepository{ctrl: ctrl}
	mock.recorder = &MockAuditRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuditRepository) EXPECT() *MockAuditRepositoryMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockAuditRepository) List(limit int) ([]*domain.AuthEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", limit)
	ret0, _ := ret[0].([]*domain.AuthEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockAuditRepositoryMockRecorder) List(limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockAuditRepository)(nil).List), limit)
}

// ListForUser mocks base method.
func (m *MockAuditRepository) ListForUser(userID string, limit int) ([]*domain.AuthEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListForUser", userID, limit)
	ret0, _ := ret[0].([]*domain.AuthEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListForUser indicates an expected call of ListForUser.
func (mr *MockAuditRepositoryMockRecorder) ListForUser(userID, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListForUser", reflect.TypeOf((*MockAuditRepository)(nil).ListForUser), userID, limit)
}

// CountFiltered mocks base method.
func (m *MockAuditRepository) CountFiltered(userID, eventType string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountFiltered", userID, eventType)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountFiltered indicates an expected call of CountFiltered.
func (mr *MockAuditRepositoryMockRecorder) CountFiltered(userID, eventType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountFiltered", reflect.TypeOf((*MockAuditRepository)(nil).CountFiltered), userID, eventType)
}

// ListFiltered mocks base method.
func (m *MockAuditRepository) ListFiltered(userID, eventType string, limit, offset int) ([]*domain.AuthEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFiltered", userID, eventType, limit, offset)
	ret0, _ := ret[0].([]*domain.AuthEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFiltered indicates an expected call of ListFiltered.
func (mr *MockAuditRepositoryMockRecorder) ListFiltered(userID, eventType, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFiltered", reflect.TypeOf((*MockAuditRepository)(nil).ListFiltered), userID, eventType, limit, offset)
}

// Record mocks base method.
func (m *MockAuditRepository) Record(event *domain.AuthEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Record", event)
	ret0, _ := ret[0].(error)
	return ret0
}

// Record indicates an expected call of Record.
func (mr *MockAuditRepositoryMockRecorder) Record(event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Record", reflect.TypeOf((*MockAuditRepository)(nil).Record), event)
}
