// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/sweeney/identity/internal/service (interfaces: WebAuthnServicer)
//
// Generated by this command:
//
//	mockgen -destination=../mocks/mock_webauthn_service.go -package=mocks github.com/sweeney/identity/internal/service WebAuthnServicer
//

// Package mocks is a generated GoMock package.
package mocks

import (
	http "net/http"
	reflect "reflect"

	protocol "github.com/go-webauthn/webauthn/protocol"
	domain "github.com/sweeney/identity/internal/domain"
	service "github.com/sweeney/identity/internal/service"
	gomock "go.uber.org/mock/gomock"
)

// MockWebAuthnServicer is a mock of WebAuthnServicer interface.
type MockWebAuthnServicer struct {
	ctrl     *gomock.Controller
	recorder *MockWebAuthnServicerMockRecorder
	isgomock struct{}
}

// MockWebAuthnServicerMockRecorder is the mock recorder for MockWebAuthnServicer.
type MockWebAuthnServicerMockRecorder struct {
	mock *MockWebAuthnServicer
}

// NewMockWebAuthnServicer creates a new mock instance.
func NewMockWebAuthnServicer(ctrl *gomock.Controller) *MockWebAuthnServicer {
	mock := &MockWebAuthnServicer{ctrl: ctrl}
	mock.recorder = &MockWebAuthnServicerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWebAuthnServicer) EXPECT() *MockWebAuthnServicerMockRecorder {
	return m.recorder
}

// BeginLogin mocks base method.
func (m *MockWebAuthnServicer) BeginLogin(username string) (*protocol.CredentialAssertion, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginLogin", username)
	ret0, _ := ret[0].(*protocol.CredentialAssertion)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// BeginLogin indicates an expected call of BeginLogin.
func (mr *MockWebAuthnServicerMockRecorder) BeginLogin(username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginLogin", reflect.TypeOf((*MockWebAuthnServicer)(nil).BeginLogin), username)
}

// BeginRegistration mocks base method.
func (m *MockWebAuthnServicer) BeginRegistration(userID string) (*protocol.CredentialCreation, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginRegistration", userID)
	ret0, _ := ret[0].(*protocol.CredentialCreation)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// BeginRegistration indicates an expected call of BeginRegistration.
func (mr *MockWebAuthnServicerMockRecorder) BeginRegistration(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginRegistration", reflect.TypeOf((*MockWebAuthnServicer)(nil).BeginRegistration), userID)
}

// DeleteCredential mocks base method.
func (m *MockWebAuthnServicer) DeleteCredential(userID, credentialID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCredential", userID, credentialID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCredential indicates an expected call of DeleteCredential.
func (mr *MockWebAuthnServicerMockRecorder) DeleteCredential(userID, credentialID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCredential", reflect.TypeOf((*MockWebAuthnServicer)(nil).DeleteCredential), userID, credentialID)
}

// FinishLogin mocks base method.
func (m *MockWebAuthnServicer) FinishLogin(challengeID string, r *http.Request, deviceHint, clientIP string) (*service.LoginResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FinishLogin", challengeID, r, deviceHint, clientIP)
	ret0, _ := ret[0].(*service.LoginResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FinishLogin indicates an expected call of FinishLogin.
func (mr *MockWebAuthnServicerMockRecorder) FinishLogin(challengeID, r, deviceHint, clientIP any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FinishLogin", reflect.TypeOf((*MockWebAuthnServicer)(nil).FinishLogin), challengeID, r, deviceHint, clientIP)
}

// FinishRegistration mocks base method.
func (m *MockWebAuthnServicer) FinishRegistration(userID, challengeID, name string, r *http.Request) (*domain.WebAuthnCredential, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FinishRegistration", userID, challengeID, name, r)
	ret0, _ := ret[0].(*domain.WebAuthnCredential)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FinishRegistration indicates an expected call of FinishRegistration.
func (mr *MockWebAuthnServicerMockRecorder) FinishRegistration(userID, challengeID, name, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FinishRegistration", reflect.TypeOf((*MockWebAuthnServicer)(nil).FinishRegistration), userID, challengeID, name, r)
}

// ListCredentials mocks base method.
func (m *MockWebAuthnServicer) ListCredentials(userID string) ([]*domain.WebAuthnCredential, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCredentials", userID)
	ret0, _ := ret[0].([]*domain.WebAuthnCredential)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCredentials indicates an expected call of ListCredentials.
func (mr *MockWebAuthnServicerMockRecorder) ListCredentials(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCredentials", reflect.TypeOf((*MockWebAuthnServicer)(nil).ListCredentials), userID)
}

// RenameCredential mocks base method.
func (m *MockWebAuthnServicer) RenameCredential(userID, credentialID, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RenameCredential", userID, credentialID, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// RenameCredential indicates an expected call of RenameCredential.
func (mr *MockWebAuthnServicerMockRecorder) RenameCredential(userID, credentialID, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RenameCredential", reflect.TypeOf((*MockWebAuthnServicer)(nil).RenameCredential), userID, credentialID, name)
}
