// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/sweeney/identity/internal/service (interfaces: AuthServicer)
//
// Generated by this command:
//
//	mockgen -destination=../mocks/mock_auth_service.go -package=mocks github.com/sweeney/identity/internal/service AuthServicer
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	service "github.com/sweeney/identity/internal/service"
	gomock "go.uber.org/mock/gomock"
)

// MockAuthServicer is a mock of AuthServicer interface.
type MockAuthServicer struct {
	ctrl     *gomock.Controller
	recorder *MockAuthServicerMockRecorder
	isgomock struct{}
}

// MockAuthServicerMockRecorder is the mock recorder for MockAuthServicer.
type MockAuthServicerMockRecorder struct {
	mock *MockAuthServicer
}

// NewMockAuthServicer creates a new mock instance.
func NewMockAuthServicer(ctrl *gomock.Controller) *MockAuthServicer {
	mock := &MockAuthServicer{ctrl: ctrl}
	mock.recorder = &MockAuthServicerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthServicer) EXPECT() *MockAuthServicerMockRecorder {
	return m.recorder
}

// AuthorizeUser mocks base method.
func (m *MockAuthServicer) AuthorizeUser(username, password, clientIP string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AuthorizeUser", username, password, clientIP)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AuthorizeUser indicates an expected call of AuthorizeUser.
func (mr *MockAuthServicerMockRecorder) AuthorizeUser(username, password, clientIP any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AuthorizeUser", reflect.TypeOf((*MockAuthServicer)(nil).AuthorizeUser), username, password, clientIP)
}

// IssueTokensForUser mocks base method.
func (m *MockAuthServicer) IssueTokensForUser(userID string) (*service.LoginResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IssueTokensForUser", userID)
	ret0, _ := ret[0].(*service.LoginResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IssueTokensForUser indicates an expected call of IssueTokensForUser.
func (mr *MockAuthServicerMockRecorder) IssueTokensForUser(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IssueTokensForUser", reflect.TypeOf((*MockAuthServicer)(nil).IssueTokensForUser), userID)
}

// Login mocks base method.
func (m *MockAuthServicer) Login(username, password, deviceHint, clientIP string) (*service.LoginResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", username, password, deviceHint, clientIP)
	ret0, _ := ret[0].(*service.LoginResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockAuthServicerMockRecorder) Login(username, password, deviceHint, clientIP any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockAuthServicer)(nil).Login), username, password, deviceHint, clientIP)
}

// Logout mocks base method.
func (m *MockAuthServicer) Logout(userID, rawRefreshToken string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Logout", userID, rawRefreshToken)
	ret0, _ := ret[0].(error)
	return ret0
}

// Logout indicates an expected call of Logout.
func (mr *MockAuthServicerMockRecorder) Logout(userID, rawRefreshToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logout", reflect.TypeOf((*MockAuthServicer)(nil).Logout), userID, rawRefreshToken)
}

// Refresh mocks base method.
func (m *MockAuthServicer) Refresh(rawRefreshToken string) (*service.LoginResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Refresh", rawRefreshToken)
	ret0, _ := ret[0].(*service.LoginResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Refresh indicates an expected call of Refresh.
func (mr *MockAuthServicerMockRecorder) Refresh(rawRefreshToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Refresh", reflect.TypeOf((*MockAuthServicer)(nil).Refresh), rawRefreshToken)
}
