// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/sweeney/identity/internal/domain (interfaces: TokenRepository)
//
// Generated by this command:
//
//	mockgen -destination=../mocks/mock_token_repository.go -package=mocks github.com/sweeney/identity/internal/domain TokenRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	domain "github.com/sweeney/identity/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockTokenRepository is a mock of TokenRepository interface.
type MockTokenRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTokenRepositoryMockRecorder
	isgomock struct{}
}

// MockTokenRepositoryMockRecorder is the mock recorder for MockTokenRepository.
type MockTokenRepositoryMockRecorder struct {
	mock *MockTokenRepository
}

// NewMockTokenRepository creates a new mock instance.
func NewMockTokenRepository(ctrl *gomock.Controller) *MockTokenRepository {
	mock := &MockTokenRepository{ctrl: ctrl}
	mock.recorder = &MockTokenRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenRepository) EXPECT() *MockTokenRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockTokenRepository) Create(token *domain.RefreshToken) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", token)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockTokenRepositoryMockRecorder) Create(token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTokenRepository)(nil).Create), token)
}

// DeleteExpiredAndOldRevoked mocks base method.
func (m *MockTokenRepository) DeleteExpiredAndOldRevoked(retentionDays int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteExpiredAndOldRevoked", retentionDays)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteExpiredAndOldRevoked indicates an expected call of DeleteExpiredAndOldRevoked.
func (mr *MockTokenRepositoryMockRecorder) DeleteExpiredAndOldRevoked(retentionDays any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteExpiredAndOldRevoked", reflect.TypeOf((*MockTokenRepository)(nil).DeleteExpiredAndOldRevoked), retentionDays)
}

// GetByHash mocks base method.
func (m *MockTokenRepository) GetByHash(tokenHash string) (*domain.RefreshToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByHash", tokenHash)
	ret0, _ := ret[0].(*domain.RefreshToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByHash indicates an expected call of GetByHash.
func (mr *MockTokenRepositoryMockRecorder) GetByHash(tokenHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByHash", reflect.TypeOf((*MockTokenRepository)(nil).GetByHash), tokenHash)
}

// RevokeAllForUser mocks base method.
func (m *MockTokenRepository) RevokeAllForUser(userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeAllForUser", userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeAllForUser indicates an expected call of RevokeAllForUser.
func (mr *MockTokenRepositoryMockRecorder) RevokeAllForUser(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeAllForUser", reflect.TypeOf((*MockTokenRepository)(nil).RevokeAllForUser), userID)
}

// RevokeByID mocks base method.
func (m *MockTokenRepository) RevokeByID(id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeByID", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeByID indicates an expected call of RevokeByID.
func (mr *MockTokenRepositoryMockRecorder) RevokeByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeByID", reflect.TypeOf((*MockTokenRepository)(nil).RevokeByID), id)
}

// RevokeFamilyByHash mocks base method.
func (m *MockTokenRepository) RevokeFamilyByHash(tokenHash string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeFamilyByHash", tokenHash)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeFamilyByHash indicates an expected call of RevokeFamilyByHash.
func (mr *MockTokenRepositoryMockRecorder) RevokeFamilyByHash(tokenHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeFamilyByHash", reflect.TypeOf((*MockTokenRepository)(nil).RevokeFamilyByHash), tokenHash)
}

// Rotate mocks base method.
func (m *MockTokenRepository) Rotate(oldTokenID string, newToken *domain.RefreshToken) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rotate", oldTokenID, newToken)
	ret0, _ := ret[0].(error)
	return ret0
}

// Rotate indicates an expected call of Rotate.
func (mr *MockTokenRepositoryMockRecorder) Rotate(oldTokenID, newToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rotate", reflect.TypeOf((*MockTokenRepository)(nil).Rotate), oldTokenID, newToken)
}
