// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/sweeney/identity/internal/domain (interfaces: OAuthClientRepository)
//
// Generated by this command:
//
//	mockgen -destination=../mocks/mock_oauth_client_repository.go -package=mocks github.com/sweeney/identity/internal/domain OAuthClientRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	domain "github.com/sweeney/identity/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockOAuthClientRepository is a mock of OAuthClientRepository interface.
type MockOAuthClientRepository struct {
	ctrl     *gomock.Controller
	recorder *MockOAuthClientRepositoryMockRecorder
	isgomock struct{}
}

// MockOAuthClientRepositoryMockRecorder is the mock recorder for MockOAuthClientRepository.
type MockOAuthClientRepositoryMockRecorder struct {
	mock *MockOAuthClientRepository
}

// NewMockOAuthClientRepository creates a new mock instance.
func NewMockOAuthClientRepository(ctrl *gomock.Controller) *MockOAuthClientRepository {
	mock := &MockOAuthClientRepository{ctrl: ctrl}
	mock.recorder = &MockOAuthClientRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOAuthClientRepository) EXPECT() *MockOAuthClientRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockOAuthClientRepository) Create(client *domain.OAuthClient) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", client)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockOAuthClientRepositoryMockRecorder) Create(client any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockOAuthClientRepository)(nil).Create), client)
}

// Delete mocks base method.
func (m *MockOAuthClientRepository) Delete(id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockOAuthClientRepositoryMockRecorder) Delete(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockOAuthClientRepository)(nil).Delete), id)
}

// GetByID mocks base method.
func (m *MockOAuthClientRepository) GetByID(id string) (*domain.OAuthClient, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", id)
	ret0, _ := ret[0].(*domain.OAuthClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockOAuthClientRepositoryMockRecorder) GetByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockOAuthClientRepository)(nil).GetByID), id)
}

// List mocks base method.
func (m *MockOAuthClientRepository) List() ([]*domain.OAuthClient, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List")
	ret0, _ := ret[0].([]*domain.OAuthClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockOAuthClientRepositoryMockRecorder) List() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockOAuthClientRepository)(nil).List))
}

// Update mocks base method.
func (m *MockOAuthClientRepository) Update(client *domain.OAuthClient) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", client)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockOAuthClientRepositoryMockRecorder) Update(client any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockOAuthClientRepository)(nil).Update), client)
}
