-- RFC 8628 Device Authorization Grant + pre-baked claim codes for screenless devices.
--
-- oauth_claim_codes holds long-lived codes printed on device stickers. Generated by
-- an admin against a specific OAuth client. On first bind a claim_code is tied to a
-- user; subsequent device_authorization requests using the same claim_code approve
-- automatically (no user interaction needed) until the claim_code is revoked.
--
-- oauth_device_codes tracks an in-flight device authorization session. It is created
-- by POST /oauth/device_authorization (standard flow) or POST /oauth/device/claim
-- (claim-code flow). The device polls POST /oauth/token with the device_code and
-- receives tokens once a user has approved the user_code on the verification page.
CREATE TABLE IF NOT EXISTS oauth_claim_codes (
    id            TEXT PRIMARY KEY,
    code_hash     TEXT NOT NULL UNIQUE,                      -- SHA-256 hex of the claim_code (what's on the sticker)
    client_id     TEXT NOT NULL REFERENCES oauth_clients(id) ON DELETE CASCADE,
    label         TEXT NOT NULL DEFAULT '',                  -- admin-friendly label, e.g. "Kitchen sensor"
    bound_user_id TEXT REFERENCES users(id) ON DELETE SET NULL,  -- NULL until first bind
    created_at    TEXT NOT NULL,
    bound_at      TEXT,
    revoked_at    TEXT                                       -- non-null = revoked; device polls will fail
);

CREATE TABLE IF NOT EXISTS oauth_device_codes (
    id               TEXT PRIMARY KEY,
    device_code_hash TEXT NOT NULL UNIQUE,                   -- SHA-256 hex of the device_code (polling secret)
    user_code        TEXT NOT NULL UNIQUE,                   -- 8-char user-visible code (XXXX-XXXX)
    client_id        TEXT NOT NULL REFERENCES oauth_clients(id) ON DELETE CASCADE,
    claim_code_id    TEXT REFERENCES oauth_claim_codes(id) ON DELETE SET NULL,  -- NULL for standard flow
    scope            TEXT NOT NULL DEFAULT '',
    status           TEXT NOT NULL DEFAULT 'pending',        -- pending | approved | denied
    user_id          TEXT REFERENCES users(id) ON DELETE CASCADE,  -- populated on approval
    issued_at        TEXT NOT NULL,
    expires_at       TEXT NOT NULL,
    last_polled_at   TEXT,
    poll_interval    INTEGER NOT NULL DEFAULT 5,             -- seconds between allowed polls
    consumed_at      TEXT                                    -- non-null once tokens have been issued; code is then dead
);

CREATE INDEX IF NOT EXISTS idx_oauth_claim_codes_code_hash     ON oauth_claim_codes(code_hash);
CREATE INDEX IF NOT EXISTS idx_oauth_claim_codes_client_id     ON oauth_claim_codes(client_id);
CREATE INDEX IF NOT EXISTS idx_oauth_device_codes_user_code    ON oauth_device_codes(user_code);
CREATE INDEX IF NOT EXISTS idx_oauth_device_codes_device_hash  ON oauth_device_codes(device_code_hash);
CREATE INDEX IF NOT EXISTS idx_oauth_device_codes_expires_at   ON oauth_device_codes(expires_at);
